name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Capture untracked files before checks
        run: git ls-files --others --exclude-standard > untracked_before.txt

      - name: Run checks
        run: npm run check

      - name: Check for new untracked files
        run: |
          # Create list of untracked files after checks
          git ls-files --others --exclude-standard > untracked_after.txt

          # Find new files (files in after but not in before)
          NEW_FILES=$(comm -13 untracked_before.txt untracked_after.txt)

          # Check if there are any new untracked files
          if [ -n "$NEW_FILES" ]; then
            echo "❌ New files were generated during the check process but are not included in the PR:"
            echo "$NEW_FILES"
            echo "Please add these files to your PR or add them to .gitignore"
            exit 1
          else
            echo "✅ No new untracked files were generated during checks"
          fi
