name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm run check

      - name: Check for untracked files
        run: |
          # Check if there are new untracked files after running checks
          if [ -n "$(git ls-files --others --exclude-standard)" ]; then
            echo "❌ New files were generated during the check process but are not included in the PR:"
            git ls-files --others --exclude-standard
            echo "Please add these files to your PR or add them to .gitignore"
            exit 1
          fi
