name: Release & Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.2.3)'
        required: true
      confirm:
        description: 'Type "RELEASE" to confirm publishing to npm'
        required: true

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm == 'RELEASE' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci --force

      - name: Build package
        run: npm run build

      - name: Format version
        id: format
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if [[ ! $VERSION =~ ^v ]]; then
            VERSION="v$VERSION"
          fi
          echo "FORMATTED_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check release notes file
        id: check_notes
        run: |
          if [ -f "releases/${{ env.FORMATTED_VERSION }}.txt" ]; then
            echo "NOTES_FILE=releases/${{ env.FORMATTED_VERSION }}.txt" >> $GITHUB_ENV
            echo "NOTES_EXIST=true" >> $GITHUB_OUTPUT
          else
            echo "No release notes file found at releases/${{ env.FORMATTED_VERSION }}.txt"
            echo "NOTES_EXIST=false" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Validate package version
        run: |
          PACKAGE_VERSION="v$(node -p "require('./package.json').version")"
          if [ "$PACKAGE_VERSION" != "${{ env.FORMATTED_VERSION }}" ]; then
            echo "Error: Requested version (${{ env.FORMATTED_VERSION }}) does not match package.json version ($PACKAGE_VERSION)"
            exit 1
          fi

      # - name: Publish to NPM
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.FORMATTED_VERSION }}
          body_path: ${{ env.NOTES_FILE }}
          tag_name: ${{ env.FORMATTED_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
