name: Run Tests

on:
  push:
    branches: [ '*' ]  # Run on all branches
  workflow_dispatch:   # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Capture untracked files before checks
      run: git ls-files --others --exclude-standard > untracked_before.txt

    - name: Run checks
      run: npm run check

    - name: Check for new untracked files
      run: |
        # Create list of untracked files after checks
        git ls-files --others --exclude-standard > untracked_after.txt

        # Find new files (files in after but not in before)
        # Using a safer approach to filter out temporary files
        NEW_FILES=$(comm -13 untracked_before.txt untracked_after.txt | grep -v "untracked_\(before\|after\)\.txt" || true)

        # Trim whitespace
        NEW_FILES=$(echo "$NEW_FILES" | sed '/^$/d')

        # Check if there are any new untracked files
        if [ -n "$NEW_FILES" ]; then
          echo "❌ New files were generated during the check process but are not included in the PR:"
          echo "$NEW_FILES"
          echo "Please add these files to your PR or add them to .gitignore"
          exit 1
        else
          echo "✅ No new untracked files were generated during checks"
        fi

        # Clean up temporary files
        rm -f untracked_before.txt untracked_after.txt